---
- name: start/stop Nginx Service
  hosts: ubuntu
  become: yes
  tasks:
    - name: nginx service
      service_facts:
    - name: Start the nginx service if it is stopped
      service:
        name: nginx
        state: started
      when: "'nginx' in services and services['nginx'].state == 'stopped'"

    - name: Stop the nginx service if it is running
      service:
        name: nginx
        state: stopped
      when: "'nginx' in services and services['nginx'].state == 'running'"
