---
- name: uninstall apache
  hosts: ubuntu
  become: yes
  tasks:
    - name: stop apache
      service: 
        name: apache2
        state: stopped
    - name: uninstall apache
      apt:
        name: apache2
        state: absent